{% set version = "4.0" %}

package:
  name: gembs-rs
  version: {{ version }}

source:
  url: https://github.com/heathsc/gemBS-rs/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d2e4f844e4a381e5a9087c27ed67751ef2a3a2c2a97b02204ff6a483cad95cc9
 
build:
  number: 0
  run_exports:
    - {{ pin_subpackage("gembs-rs", max_pin="x") }}
  script: cargo build --release $prefix/bin &&
        	cp target/release/gem_bs $prefix/bin/gemBS &&
        	cp target/release/read_filter $prefix/bin/ &&
        	cp target/release/bs_call $prefix/bin/ &&
        	cp target/release/snpxtr $prefix/bin/ &&
        	cp target/release/mextr $prefix/bin/ &&
        	cp target/release/dbsnp_index $prefix/bin/

requirements:
  build:
    - make
    - autoconf
    - automake
    - {{ compiler('c') }}
    - wget
    - zlib
  host:
    - pip
    - python
    - htslib
    - openssl
    - bzip2
    - zlib
  run:
    - gem3-mapper
    - python
    - matplotlib-base
    - multiprocess
    - pigz
    - openssl
    - bzip2
    - zlib
    - htslib
    - matplotlib-base
    - multiprocess
    - samtools
    - bcftools
    - bs_call
    - gem3-mapper
    - setuptools


test:
  commands:
    - gemBS --version

about:
  home: https://github.com/heathsc/gemBS-rs
  license: BSD 3-Clause License
  summary: gemBS-rs new rust implementation of gemBS for analysis of DNA methylation from WGBS data
  license_family: BSD
  license_file: LICENSE
  doc_url: http://statgen.cnag.cat/gemBS/UserGuide/_build/html/index.html
