{% set version = "4.0" %}

package:
  name: gembs-rs
  version: {{ version }}

source:
  url: https://github.com/heathsc/gemBS-rs/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d2e4f844e4a381e5a9087c27ed67751ef2a3a2c2a97b02204ff6a483cad95cc9
 
build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage("varlociraptor", max_pin="x") }}

requirements:
  build:
    -  build-essential 
    -  git 
    -  autoconf 
    -  wget 
    -  lbzip2 
    -  pkg-config 
    -  cmake
    -  zlib1g-dev 
    -  libbz2-dev 
    -  libexpat1-dev
    -  libncurses5-dev 
    -  liblzma-dev 
    -  libssl-dev 
    -  libcurl4-openssl-dev 
    -  curl
    -  libfreetype6-dev 
    -  libfontconfig1-dev
  host:
    -  rustc
    -  rustup
  run:
    -  rustc
    -  rustup


test:
  commands:
    - gemBS --version

about:
  home: https://github.com/heathsc/gemBS-rs
  license: BSD 3-Clause License
  summary: 'gemBS: high-throughput analysis of DNA methylation from whole genome bisulfite sequencing data'
  license_family: BSD
  license_file: LICENSE
  doc_url: http://statgen.cnag.cat/gemBS/UserGuide/_build/html/index.html
    - doi:10.7287/peerj.preprints.970v1
