package:
  name: gembs-rs
  version: "4.0.4"

source:
  git_url: https://github.com/heathsc/gemBS-rs.git
  git_tag: v4.0.4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - rust
    - cargo
    - cmake
    - make
  host:
    - python
    - pip
  run:
    - python
    - samtools
    - bcftools
    - htslib

test:
  commands:
    - gemBS --version

about:
  home: https://github.com/heathsc/gemBS-rs
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "A high performance bioinformatic pipeline for DNA methylation data analysis."
  description: |
    gemBS is a high performance bioinformatic pipeline designed for highthroughput analysis of DNA methylation data from whole genome bisulfites sequencing data (WGBS). It combines GEM3, a high performance read aligner and bs_call, a high performance variant and methylation caller, into a streamlined and efficient pipeline for bisulfite sequence analysis.

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btx046
  recipe-maintainers:
    - your-github-username
