{% set version = "4.0" %}

package:
  name: gembs-rs
  version: {{ version }}

source:
  url: https://github.com/heathsc/gemBS-rs/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d2e4f844e4a381e5a9087c27ed67751ef2a3a2c2a97b02204ff6a483cad95cc9

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("gembs-rs", max_pin="x") }}
  ignore_run_exports_from:
    # Uses the static libraries of the following packages:
    - zlib

requirements:
  build:
    # - make
    # - cmake >3.5
    # - autoconf
    # - automake
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    # - htslib
    # - openssl
    # - bzip2
    - zlib
    - freetype
    # - expat
    - fontconfig
    # - ncurses
    # - zstd
    - pkg-config
  run:
    - gem3-mapper
    - pigz
    - samtools
    - bcftools
    - bs_call

test:
  commands:
    - gemBS --version
    - |
      printf %s\\n 'barcode,dataset' > metadata.csv
      printf %s\\n '[index]' 'reference = genome.fa' > config
      printf '>seq\n%10000000s\n' | tr ' ' A > genome.fa
      gemBS --loglevel trace prepare --config config --text-metadata metadata.csv
      gemBS --loglevel trace call 2>&1 | { ! grep Error ; }

about:
  home: https://github.com/heathsc/gemBS-rs
  license: BSD 3-Clause License
  summary: High throughput processing for DNA methylation data from Bisulfite Sequencing
  license_family: BSD
  license_file: LICENSE
  doc_url: https://pubmed.ncbi.nlm.nih.gov/30137223/
