{% set version = "4.0" %}

package:
  name: gembs-rs
  version: {{ version }}

source:
  url: https://github.com/heathsc/gemBS-rs/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d2e4f844e4a381e5a9087c27ed67751ef2a3a2c2a97b02204ff6a483cad95cc9

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("gembs-rs", max_pin="x") }}

requirements:
  build:
    - make
    - cmake >3.5
    - autoconf
    - automake
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - pip
    - python
    - htslib
    - openssl
    - bzip2
    - zlib
    - freetype
    - expat
    - fontconfig
    - ncurses
    - zstd
    - pkg-config
    - htslib
  run:
    - gem3-mapper
    - python
    - matplotlib-base
    - multiprocess
    - pigz
    - openssl
    - bzip2
    - zlib
    - matplotlib-base
    - multiprocess
    - samtools
    - bcftools
    - bs_call
    - setuptools

test:
  commands:
    - gemBS --version

about:
  home: https://github.com/heathsc/gemBS-rs
  license: BSD 3-Clause License
  summary: High throughput processing for DNA methylation data from Bisulfite Sequencing
  license_family: BSD
  license_file: LICENSE
  doc_url: https://pubmed.ncbi.nlm.nih.gov/30137223/
